# Generated by Django 6.0.6 on 2026-06-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('html', 'HTML Scraping'), ('api', 'API')], default='html', max_length=10)),
                ('scrape_config', models.JSONField(blank=True, default=dict, help_text='CSS selectors and patterns for scraping this source')),
                ('is_active', models.BooleanField(default=True)),
                ('scrape_interval', models.PositiveIntegerField(default=60, help_text='Minutes between scrape attempts')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.source')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
